version: 'latest'

services:  
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Warsaw
       ports:
            - 5055:5055
       volumes:
            - ./jellyseerr/config:/app/config
       restart: always
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./jellyfin/library:/config
      - ./jellyfin/tvseries:/data/tvshows
      - ./jellyfin/movies:/data/movies
      - ./jellyfin/anime:/data/anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: always